"use client";

import { useState } from "react";
import Link from "next/link";
import CustomerRequestModal from "@/components/customer/CustomerRequestModal";

const recent = [
  ["Gasabo, Kimihurura", "URGENT", "In progress", "bg-[#edf3ff] text-[#3670df]"],
  ["Gasabo, Remera", "Today", "Awaiting review", "bg-[#f0eaff] text-[#7b43e7]"],
  ["Gasabo, Kacyiru", "Can wait", "Completed", "bg-[#e6f7ed] text-[#238156]"],
];

export default function CustomerDashboard() {
  const [modal, setModal] = useState(false);
  return <><section className="w-full">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-[26px] font-bold tracking-tight sm:text-[30px]">My Dashboard</h1><p className="text-[14px] text-[#79918f]">Delice Uwase · Gasabo, Kimihurura</p></div><button onClick={() => setModal(true)} className="w-full rounded-md bg-[#ff5b2b] px-6 py-3 text-[14px] font-semibold text-white shadow-md sm:w-auto">＋&nbsp; New Request</button></div>
    <div className="mt-6 flex flex-col items-start gap-4 rounded-xl border border-[#d8c8ff] bg-[#f7f3ff] px-5 py-4 sm:flex-row sm:items-center"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full border border-[#cdb5ff] text-xl text-[#783ee4]">☆</span><div className="flex-1"><h2 className="text-[16px] font-bold text-[#7438d9]">Your review is required</h2><p className="mt-1 text-[14px] text-[#63716f]">Job completed: <b>Electrical</b> request on Jul 14, 2025. Rate your experience to allow the technician to accept new jobs.</p></div><button className="w-full rounded-md bg-[#7435e8] px-5 py-3 text-[13px] font-semibold text-white sm:w-auto">☆ &nbsp; Leave review</button></div>
    <div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4 xl:gap-[18px]">{[["Active requests", "2", "In progress or pending", "text-[#ff6b42]"], ["Completed jobs", "1", "All time", "text-[#339268]"], ["Pending reviews", "1", "Action required", "text-[#7435e8]"], ["Technicians hired", "6", "Since joining", "text-[#4774dd]"]].map(([label, value, hint, color]) => <div key={label} className="h-[130px] rounded-xl border border-[#e6eceb] bg-white p-6 shadow-sm"><p className="text-[14px] text-[#75908d]">{label}</p><p className="mt-3 text-[32px] font-bold leading-7 text-slate-900">{value}</p><p className={`mt-2 text-[13px] font-semibold ${color}`}>{hint}</p></div>)}</div>
    <div className="mt-7 grid grid-cols-1 gap-4 md:grid-cols-3 xl:gap-[18px]">{[["＋", "New Request", "Submit a maintenance job"], ["⌕", "Find Technicians", "Browse & filter"], ["▣", "My Requests", "Track active jobs"]].map(([icon, title, text], i) => <Link key={title} href={i === 0 ? "#" : i === 2 ? "/dashboard/customer/requests" : "/dashboard/customer/technicians"} onClick={i === 0 ? e => { e.preventDefault(); setModal(true); } : undefined} className="h-[138px] rounded-xl border border-[#e6eceb] bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[#fff0eb] text-xl text-[#ff7652]">{icon}</span><h2 className="mt-3 text-[17px] font-bold text-slate-800">{title}</h2><p className="mt-1 text-[14px] text-[#78918e]">{text}</p></Link>)}</div>
    <div className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-[15px] font-bold">Recent activity</h2><Link href="/dashboard/customer/requests" className="text-[10px] font-semibold text-[#f36b40]">View all　›</Link></div><div className="space-y-2">{recent.map(([place, urgency, status, style], i) => <div key={place} className="rounded-xl border border-[#f0e0da] border-t-2 border-t-[#ff5b2b] bg-white px-4 py-3 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#ffe9e3] text-[8px] font-bold text-[#ff5b2b]">DU</span><div><h3 className="text-[11px] font-bold">Delice Uwase</h3><p className="text-[9px] text-[#76908d]">⌾ {place}</p></div></div><div className="flex gap-2"><span className="rounded-full bg-[#fff0ee] px-2 py-1 text-[8px] font-bold text-[#ff5b2b]">♨ {urgency}</span><span className={`rounded-full px-2 py-1 text-[8px] font-semibold ${style}`}>{status}</span></div></div>{i === 1 && <div className="mt-2 flex items-center rounded border border-[#e4d9ff] bg-[#f9f6ff] px-3 py-2 text-[9px] text-[#7038e1]">☆ <b className="ml-1">Customer review required to complete this job</b><button className="ml-auto rounded bg-[#7435e8] px-3 py-1.5 text-[8px] font-semibold text-white">Leave review</button></div>}</div>)}</div></div>
  </section><CustomerRequestModal open={modal} onClose={() => setModal(false)} /></>;
}
