"use client";

import { useState } from "react";
import { Search, X } from "lucide-react";

const users = [
  ["DU", "Delice Uwase", "Customer", "Gasabo, Kimihurura", "Active"], ["EN", "Eric Nshimiyimana", "Technician", "Gasabo, Kimihurura", "Active"], ["BL", "BuildFix Ltd", "Company", "Gasabo, Kacyiru", "Active"], ["BK", "Beatrice Kayitesi", "Customer", "Nyarugenge", "Active"], ["SI", "Solange Ineza", "Technician", "Nyarugenge", "Pending"],
];
const roleStyle: Record<string, string> = { Customer: "bg-slate-100 text-slate-500", Technician: "bg-orange-50 text-[#ff6224]", Company: "bg-blue-50 text-blue-600" };

export default function UsersPage() {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<(typeof users)[number] | null>(null);
  const shown = users.filter((user) => user[1].toLowerCase().includes(query.toLowerCase()) || user[2].toLowerCase().includes(query.toLowerCase()));
  return <main className="min-h-screen bg-[#f5f7f6] p-7 lg:p-10"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-heading text-2xl font-extrabold text-[#132d2a]">Users</h1><p className="mt-1 text-sm text-slate-500">All registered accounts</p></div><label className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><Search className="h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search users" className="w-40 outline-none" /></label></header><div className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-[minmax(220px,2fr)_minmax(120px,1fr)_minmax(140px,1fr)_minmax(105px,.7fr)_75px] gap-4 border-b border-slate-200 bg-slate-50 px-4 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-500"><span>User</span><span>Type</span><span>Location</span><span>Status</span><span /></div>{shown.map((user) => <div key={user[1]} className="grid grid-cols-[minmax(220px,2fr)_minmax(120px,1fr)_minmax(140px,1fr)_minmax(105px,.7fr)_75px] items-center gap-4 border-b border-slate-100 px-4 py-3 last:border-0"><div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#fff0eb] text-[10px] font-bold text-[#ff6224]">{user[0]}</span><span className="text-sm font-semibold text-[#132d2a]">{user[1]}</span></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${roleStyle[user[2]]}`}>{user[2]}</span><span className="text-xs text-slate-600">{user[3]}</span><span className={`text-xs font-medium ${user[4] === "Active" ? "text-emerald-700" : "text-slate-500"}`}>● {user[4]}</span><button onClick={() => setSelected(user)} className="rounded-md border border-slate-200 px-2 py-1.5 text-xs text-slate-600 hover:bg-slate-50">Manage</button></div>)}</div>{selected && <div role="dialog" aria-modal="true" className="fixed inset-0 z-30 grid place-items-center bg-slate-900/30 p-4"><div className="w-full max-w-sm rounded-xl bg-white p-6 shadow-xl"><button onClick={() => setSelected(null)} className="float-right text-slate-400"><X className="h-5 w-5" /></button><h2 className="text-lg font-bold">{selected[1]}</h2><p className="mt-1 text-sm text-slate-500">{selected[2]} · {selected[3]}</p><div className="mt-5 flex gap-2"><button className="rounded-lg bg-[#0f7651] px-3 py-2 text-sm font-semibold text-white">Mark active</button><button className="rounded-lg border border-rose-200 px-3 py-2 text-sm font-semibold text-rose-600">Block account</button></div></div></div>}</main>;
}
