"use client";

import { CheckCircle2, Eye, Pencil, XCircle } from "lucide-react";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import { getLocalAccounts, setAccountApproval, type LocalAccount } from "@/lib/localAuth";
import { useEffect, useState } from "react";

const queue = [["SI", "Solange Ineza", "Technician", "Painting · Nyarugenge, Nyamirambo · submitted Jul 14, 2025", "solange.i@gmail.com · +250 788 600 003 · 3 docs uploaded", "Verify"], ["IH", "Innocent Habimana", "Technician", "Plumbing · Gasabo, Kimihurura · submitted Jul 15, 2025", "innocent.h@gmail.com · +250 788 600 004 · 2 docs uploaded", "Verify"], ["CL", "CleanPro Ltd", "Company", "General Maintenance · Kicukiro, Gatenga · submitted Jul 16, 2025", "info@cleanpro.rw · +250 788 900 300 · 1 doc uploaded", "Accredit"]];
export default function VerificationQueuePage() { const [pending, setPending] = useState<LocalAccount[]>([]); const [notice, setNotice] = useState(""); useEffect(() => setPending(getLocalAccounts().filter((item) => (item.role === "technician" || item.role === "company") && item.approvalStatus === "pending")), []); const decide = (account: LocalAccount, status: "approved" | "rejected") => { setAccountApproval(account.email, status); setPending((items) => items.filter((item) => item.email !== account.email)); setNotice(`${account.name} was ${status}.`); }; const items = pending.length ? pending.map((a) => [a.name.slice(0, 2).toUpperCase(), a.name, a.role === "company" ? "Company" : "Technician", "New registration submitted for review", a.email, a.role === "company" ? "Accredit" : "Verify"] as const) : queue; return <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-7"><AdminPageHeader title="Verification Queue" description={`${pending.length} new registrations pending`} />{notice && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}<div className="mt-5 space-y-3">{items.map(([initials, name, type, subtitle, contact, action]) => <article key={contact} className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm lg:flex-row lg:items-center"><span className="grid h-10 w-10 place-items-center rounded-full bg-orange-50 text-xs font-bold text-primary">{initials}</span><div className="min-w-0 flex-1"><h2 className="font-semibold text-secondary">{name} <span className="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] text-amber-700">Pending</span></h2><p className="mt-1 text-xs text-slate-500">{subtitle}</p><p className="mt-1 text-xs text-slate-600">{contact}</p></div><div className="flex gap-2"><button className="flex items-center gap-1 rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-600"><Eye size={13} />Review</button><button onClick={() => { const account = pending.find((item) => item.email === contact); if (account) decide(account, "rejected"); }} className="flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-red-500"><XCircle size={13} />Reject</button><button onClick={() => { const account = pending.find((item) => item.email === contact); if (account) decide(account, "approved"); }} className="flex items-center gap-1 rounded-lg bg-accent px-3 py-2 text-xs font-semibold text-white"><CheckCircle2 size={13} />{action}</button></div></article>)}</div></div>; }
