"use client";

import { CheckCircle2, Eye, FileText, XCircle } from "lucide-react";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import { getLocalAccounts, setAccountApproval, type LocalAccount } from "@/lib/localAuth";
import { useEffect, useState } from "react";

function DocumentsModal({ account, onClose }: { account: LocalAccount | null; onClose: () => void }) {
  if (!account) return null;
  const documents = account.documents ?? [];
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-label="Submitted verification documents"><section className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between border-b pb-4"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Verification submission</p><h2 className="mt-1 text-xl font-bold text-secondary">{account.name}&apos;s documents</h2><p className="mt-1 text-sm text-slate-500">{account.profile?.trade || account.profile?.service || account.role} · {account.profile?.district || "Location not provided"}</p></div><button onClick={onClose} className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100">Close</button></div>{documents.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2">{documents.map(doc => <article key={doc.name} className="overflow-hidden rounded-xl border border-slate-200"><div className="flex items-center gap-2 border-b bg-slate-50 p-3 text-sm font-semibold text-slate-700"><FileText size={16}/><span className="truncate">{doc.name}</span></div>{doc.type.startsWith("image/") ? <img src={doc.dataUrl} alt={doc.name} className="h-64 w-full object-contain bg-slate-100" /> : <a href={doc.dataUrl} target="_blank" rel="noreferrer" className="grid h-64 place-items-center text-sm font-semibold text-primary underline">Open document</a>}<a href={doc.dataUrl} download={doc.name} className="block p-3 text-center text-sm font-semibold text-primary">Download</a></article>)}</div> : <p className="mt-5 rounded-lg bg-amber-50 p-4 text-sm text-amber-800">No uploaded documents are available for this older submission.</p>}</section></div>;
}

export default function VerificationQueuePage() {
  const [pending, setPending] = useState<LocalAccount[]>([]); const [notice, setNotice] = useState(""); const [reviewing, setReviewing] = useState<LocalAccount | null>(null);
  useEffect(() => setPending(getLocalAccounts().filter(item => (item.role === "technician" || item.role === "company") && item.approvalStatus === "pending")), []);
  const decide = (account: LocalAccount, status: "approved" | "rejected") => { setAccountApproval(account.email, status); setPending(items => items.filter(item => item.email !== account.email)); setReviewing(null); setNotice(`${account.name} was ${status}.`); };
  return <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-7"><AdminPageHeader title="Verification Queue" description={`${pending.length} new registrations pending`} />{notice && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}<div className="mt-5 space-y-3">{pending.map(account => <article key={account.email} className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm lg:flex-row lg:items-center"><span className="grid h-10 w-10 place-items-center rounded-full bg-orange-50 text-xs font-bold text-primary">{account.name.slice(0,2).toUpperCase()}</span><div className="min-w-0 flex-1"><h2 className="font-semibold text-secondary">{account.name} <span className="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-[10px] text-amber-700">Pending</span></h2><p className="mt-1 text-xs text-slate-500">{account.profile?.trade || account.profile?.service || account.role} · {account.profile?.district || "Location not provided"}</p><p className="mt-1 text-xs text-slate-600">{account.email} · {account.documents?.length ?? 0} document(s) uploaded</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setReviewing(account)} className="flex items-center gap-1 rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-600"><Eye size={13}/>Review documents</button><button onClick={() => decide(account, "rejected")} className="flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-red-500"><XCircle size={13}/>Reject</button><button onClick={() => decide(account, "approved")} className="flex items-center gap-1 rounded-lg bg-accent px-3 py-2 text-xs font-semibold text-white"><CheckCircle2 size={13}/>{account.role === "company" ? "Accredit" : "Verify"}</button></div></article>)}{!pending.length && <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No registrations are awaiting review.</div>}</div><DocumentsModal account={reviewing} onClose={() => setReviewing(null)}/></div>;
}
