"use client";

import { ChangeEvent, FormEvent, useRef, useState } from "react";
import { CheckCircle2, KeyRound, Save, Upload } from "lucide-react";

type CompanyForm = { company: string; owner: string; email: string; phone: string; district: string; sector: string };
const initialForm: CompanyForm = { company: "BuildFix Ltd", owner: "Jean Pierre Nkurunziza", email: "info@buildfix.rw", phone: "+250 788 100 200", district: "Gasabo", sector: "Kacyiru" };

export default function CompanySettings() {
  const [form, setForm] = useState<CompanyForm>(initialForm);
  const [logo, setLogo] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [passwords, setPasswords] = useState({ current: "", next: "", confirm: "" });
  const [passwordMessage, setPasswordMessage] = useState("");
  const fileInput = useRef<HTMLInputElement>(null);
  const update = (key: keyof CompanyForm) => (event: ChangeEvent<HTMLInputElement>) => { setForm((current) => ({ ...current, [key]: event.target.value })); setSaved(false); };
  const save = (event: FormEvent) => { event.preventDefault(); window.localStorage.setItem("maintenance-hub-company-profile", JSON.stringify({ form, logo })); setSaved(true); };
  const uploadLogo = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setLogo(URL.createObjectURL(file)); };
  const initials = form.company.split(" ").map((word) => word[0]).join("").slice(0, 2).toUpperCase();

  return <section className="mx-auto max-w-3xl"><h1 className="font-heading text-3xl font-extrabold tracking-tight text-[#102724]">Account Settings</h1><p className="mt-1 text-sm text-[#78908d]">Manage your company profile and security.</p>
    <form onSubmit={save} className="mt-7 rounded-2xl border border-[#e2e9e7] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center gap-4 border-b border-[#e7eeec] pb-6"><button type="button" onClick={() => fileInput.current?.click()} className="relative grid h-14 w-14 place-items-center overflow-hidden rounded-full bg-[#ff5a1f] text-lg font-bold text-white">{logo ? <img src={logo} alt="Company logo" className="h-full w-full object-cover" /> : initials}<span className="absolute inset-0 grid place-items-center bg-black/30 opacity-0 transition hover:opacity-100"><Upload size={16} /></span></button><input ref={fileInput} onChange={uploadLogo} accept="image/*" type="file" className="hidden" /><div><h2 className="text-xl font-bold text-[#102724]">{form.company}</h2><p className="text-sm text-[#78908d]">Company account · Click logo to upload</p></div></div>
      <h3 className="mt-7 font-bold text-[#102724]">Company and owner information</h3><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Company name" value={form.company} onChange={update("company")} /><Field label="Owner name" value={form.owner} onChange={update("owner")} /><Field label="Email address" type="email" value={form.email} onChange={update("email")} /><Field label="Phone number" value={form.phone} onChange={update("phone")} /><Field label="District" value={form.district} onChange={update("district")} /><Field label="Sector" value={form.sector} onChange={update("sector")} /></div><div className="mt-7 flex items-center gap-4"><button className="inline-flex items-center gap-2 rounded-lg bg-[#ff5a1f] px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-[#e64b15]"><Save size={16} />Save changes</button>{saved && <span role="status" className="inline-flex items-center gap-1.5 text-sm font-medium text-emerald-700"><CheckCircle2 size={16} />Changes saved</span>}</div>
    </form>
    <form onSubmit={(event) => { event.preventDefault(); setPasswordMessage(passwords.next.length < 8 ? "New password must contain at least 8 characters." : passwords.next !== passwords.confirm ? "New passwords do not match." : "Password updated successfully."); }} className="mt-5 rounded-2xl border border-[#e2e9e7] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0eb] text-[#ff5a1f]"><KeyRound size={19} /></span><div><h2 className="font-bold text-[#102724]">Change password</h2><p className="text-sm text-[#78908d]">Use at least 8 characters.</p></div></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Current password" type="password" value={passwords.current} onChange={(event) => setPasswords((current) => ({ ...current, current: event.target.value }))} placeholder="Your current password" /><Field label="New password" type="password" value={passwords.next} onChange={(event) => setPasswords((current) => ({ ...current, next: event.target.value }))} placeholder="Min. 8 characters" /><Field label="Confirm new password" type="password" value={passwords.confirm} onChange={(event) => setPasswords((current) => ({ ...current, confirm: event.target.value }))} placeholder="Repeat new password" /></div><div className="mt-6 flex items-center gap-4"><button className="inline-flex items-center gap-2 rounded-lg bg-[#ff5a1f] px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-[#e64b15]"><KeyRound size={16} />Update password</button>{passwordMessage && <span role="status" className={`text-sm font-medium ${passwordMessage === "Password updated successfully." ? "text-emerald-700" : "text-red-600"}`}>{passwordMessage}</span>}</div></form>
  </section>;
}

function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string; onChange: (event: ChangeEvent<HTMLInputElement>) => void; type?: string; placeholder?: string }) { return <label className="block text-[11px] font-bold uppercase tracking-wider text-[#78908d]">{label}<input required={type !== "password"} type={type} value={value} onChange={onChange} placeholder={placeholder} className="mt-2 w-full rounded-lg border border-[#dfe7e5] bg-[#f8faf9] px-4 py-3 text-[15px] font-normal normal-case tracking-normal text-[#263b38] outline-none focus:border-[#ff5a1f] focus:ring-2 focus:ring-orange-100" /></label>; }
