"use client";

import { useState } from "react";

type Member = { initials: string; name: string; joined: string; trade: string; email: string; phone: string; status: "Active" | "Busy"; jobs: number };
const members: Member[] = [
  { initials: "EN", name: "Eric Nshimiyimana", joined: "Joined Jan 2024", trade: "Plumbing", email: "eric.n@buildfix.rw", phone: "+250 788 111 001", status: "Active", jobs: 87 },
  { initials: "CM", name: "Claudine Mukamana", joined: "Joined Mar 2024", trade: "Electrical", email: "claudine@buildfix.rw", phone: "+250 788 111 002", status: "Busy", jobs: 63 },
  { initials: "PH", name: "Patrick Habimana", joined: "Joined May 2024", trade: "Carpentry", email: "patrick@buildfix.rw", phone: "+250 788 111 003", status: "Active", jobs: 55 },
  { initials: "AN", name: "Aline Nyirabazungu", joined: "Joined Jun 2024", trade: "Painting", email: "aline@buildfix.rw", phone: "+250 788 111 004", status: "Active", jobs: 42 },
];

function MemberModal({ member, onClose }: { member: Member | null; onClose: () => void }) {
  if (!member) return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4" role="dialog" aria-modal="true" aria-label="Technician details"><section className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#ffe9e3] font-bold text-[#ff5b2b]">{member.initials}</span><div><h2 className="text-xl font-bold">{member.name}</h2><p className="text-sm text-slate-500">{member.trade}</p></div></div><button onClick={onClose} className="text-xl text-slate-500" aria-label="Close">x</button></div><dl className="mt-6 space-y-3 rounded-xl bg-[#f6f8f8] p-4 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Email</dt><dd>{member.email}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Phone</dt><dd>{member.phone}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Completed jobs</dt><dd>{member.jobs}</dd></div></dl><button onClick={onClose} className="mt-5 w-full rounded-lg bg-[#ff5b2b] py-3 text-sm font-semibold text-white">Close details</button></section></div>;
}

export default function CompanyDashboardView() {
  const [selectedMember, setSelectedMember] = useState<Member | null>(null);
  const [addOpen, setAddOpen] = useState(false);
  return <><section className="w-full"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-[26px] font-bold tracking-tight sm:text-[30px]">Company Dashboard</h1><p className="mt-1 text-[14px] text-[#789190]">BuildFix Ltd · Accredited · Kigali, Gasabo</p></div><button onClick={() => setAddOpen(true)} className="w-full rounded-xl bg-[#ff5b2b] px-7 py-3.5 text-[14px] font-semibold text-white shadow-md sm:w-auto">+ Add Technician</button></div>
    <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4 xl:gap-[18px]">{[["Team members", "4", "Active employees", "text-[#ff5b2b]"], ["New requests", "1", "Awaiting assignment", "text-[#c55c00]"], ["Active jobs", "2", "In progress", "text-[#1d4ed8]"], ["Avg. rating", "4.8", "148 reviews", "text-[#087b50]"]].map(([label, value, hint, color]) => <div key={label} className="h-[130px] rounded-xl border border-[#e6eceb] bg-white p-6 shadow-sm"><p className="text-[14px] text-[#75908d]">{label}</p><p className="mt-3 text-[32px] font-bold leading-7">{value}</p><p className={`mt-2 text-[13px] font-semibold ${color}`}>{hint}</p></div>)}</div>
    <div className="mt-7 flex flex-col gap-3 rounded-xl border border-[#f0d58a] bg-[#fff4c9] px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-[16px] font-semibold text-[#be5a00]">! &nbsp;1 request needs assignment</p><button className="rounded-xl bg-[#bd5700] px-5 py-3 text-[14px] font-semibold text-white">Manage requests</button></div>
    <h2 className="mt-7 text-[20px] font-bold">Team Members</h2><div className="mt-5 overflow-x-auto rounded-xl border border-[#e1e8e7] bg-white shadow-sm"><table className="min-w-[1000px] w-full text-left"><thead className="border-b border-[#dce5e4] bg-[#fbfcfc] text-[13px] uppercase tracking-wider text-[#728987]"><tr>{["Technician", "Trade", "Contact", "Status", "Jobs", "Actions"].map((heading) => <th key={heading} className="px-6 py-4 font-semibold">{heading}</th>)}</tr></thead><tbody>{members.map((member) => <tr key={member.email} className="border-b border-[#e1e8e7] last:border-0"><td className="px-6 py-6"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#ffe9e3] text-[13px] font-bold text-[#ff5b2b]">{member.initials}</span><div><b className="block text-[16px]">{member.name}</b><span className="text-[13px] text-[#789190]">{member.joined}</span></div></div></td><td className="px-6 text-[16px]">{member.trade}</td><td className="px-6"><p className="text-[15px]">{member.email}</p><p className="text-[13px] text-[#789190]">{member.phone}</p></td><td className="px-6"><span className={member.status === "Active" ? "text-[#087b50]" : "text-[#ff5b2b]"}>● {member.status}</span></td><td className="px-6 text-[16px]">{member.jobs} jobs</td><td className="px-6"><div className="flex gap-2"><button onClick={() => setSelectedMember(member)} className="rounded-lg bg-[#edf4ff] px-3 py-2 text-[13px] font-semibold text-[#1d4ed8]">View details</button><button className="rounded-lg bg-[#fff3ec] px-3 py-2 text-[13px] font-semibold text-[#ff5b2b]">Modify</button></div></td></tr>)}</tbody></table></div></section>
    <MemberModal member={selectedMember} onClose={() => setSelectedMember(null)} />
    {addOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4" role="dialog" aria-modal="true" aria-label="Add technician"><form onSubmit={(event) => { event.preventDefault(); setAddOpen(false); }} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Add technician</h2><button type="button" onClick={() => setAddOpen(false)} className="text-xl text-slate-500">x</button></div><div className="mt-5 space-y-4"><input required placeholder="Full name" className="w-full rounded-lg border border-slate-200 px-4 py-3 outline-none focus:border-[#ff5b2b]" /><input required type="email" placeholder="Email address" className="w-full rounded-lg border border-slate-200 px-4 py-3 outline-none focus:border-[#ff5b2b]" /><select className="w-full rounded-lg border border-slate-200 px-4 py-3 text-slate-600"><option>Select trade</option><option>Plumbing</option><option>Electrical</option><option>Carpentry</option></select></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setAddOpen(false)} className="rounded-lg border border-slate-200 px-4 py-3 font-semibold">Cancel</button><button className="rounded-lg bg-[#ff5b2b] px-4 py-3 font-semibold text-white">Add technician</button></div></form></div>}
  </>;
}
