/* Local implementation superseded by the merged admin module.
import { BadgeCheck, Ban, FilePenLine, LogIn, Search } from "lucide-react";
const records = [[BadgeCheck, "Verification approved", "Sarah K. verified Patrick N. as a technician", "Jul 9, 2025 · 09:12", "text-emerald-600 bg-emerald-50"], [FilePenLine, "Category updated", "Sarah K. changed the Plumbing category description", "Jul 9, 2025 · 08:53", "text-blue-600 bg-blue-50"], [LogIn, "Administrator sign-in", "Sarah K. signed in from Kigali, Rwanda", "Jul 9, 2025 · 08:46", "text-slate-600 bg-slate-100"], [Ban, "Account auto-blocked", "Jeanne C. was blocked after failed login attempts", "Jul 8, 2025 · 14:05", "text-rose-600 bg-rose-50"]] as const;
export default function Page() { return <main className="min-h-screen bg-[#f5f7f6] p-7 lg:p-10"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-heading text-2xl font-extrabold text-[#132d2a]">Audit Log</h1><p className="mt-1 text-sm text-slate-500">Track important activity across the platform.</p></div><div className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-400"><Search className="h-4 w-4" />Search activity</div></header><section className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{records.map(([Icon, title, description, date, colors]) => <div key={title} className="flex items-center gap-4 border-b border-slate-100 px-5 py-4 last:border-0"><span className={`grid h-9 w-9 place-items-center rounded-lg ${colors}`}><Icon className="h-4 w-4" /></span><div className="flex-1"><p className="text-sm font-bold text-[#132d2a]">{title}</p><p className="mt-0.5 text-xs text-slate-500">{description}</p></div><span className="text-right text-xs text-slate-400">{date}</span></div>)}</section></main>; }
*/
import { Filter, Search } from "lucide-react";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
const events = [["Account verified", "Admin approved technician Solange Ineza", "Admin", "Jul 9, 2026 · 09:12"], ["Payment received", "Annual subscription payment from Eric N.", "System", "Jul 9, 2026 · 08:47"], ["Application flagged", "ID document required manual review", "System", "Jul 8, 2026 · 17:23"], ["Account blocked", "Customer account blocked after failed attempts", "System", "Jul 8, 2026 · 14:05"]];
export default function AuditLogPage() { return <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-7"><AdminPageHeader title="Audit Log" description="Track important activity across the platform" /><div className="mb-4 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><input aria-label="Search audit log" placeholder="Search activity" className="w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none focus:border-primary" /></label><button className="flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm text-slate-600"><Filter size={16} />Filter</button></div><section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{events.map(([event, description, actor, date]) => <article key={event} className="flex flex-col gap-2 border-b border-slate-100 p-4 last:border-0 sm:flex-row sm:items-center"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-orange-50 text-xs font-bold text-primary">{actor[0]}</span><div className="flex-1"><h2 className="text-sm font-semibold text-secondary">{event}</h2><p className="mt-0.5 text-xs text-slate-500">{description}</p></div><span className="text-xs text-slate-500">{actor}</span><time className="text-xs text-slate-400">{date}</time></article>)}</section></div>; }
