/* Local implementation superseded by the merged admin module.
"use client";

import { FormEvent, useState } from "react";
import { Edit3, Plus, Tags, Trash2 } from "lucide-react";

const defaults = ["Plumbing", "Electrical", "Cleaning", "Painting", "Carpentry", "Appliance repair"];
export default function CategoriesPage() { const [categories, setCategories] = useState(defaults); const [name, setName] = useState(""); const add = (e: FormEvent) => { e.preventDefault(); const value = name.trim(); if (value && !categories.some(c => c.toLowerCase() === value.toLowerCase())) { setCategories([...categories, value]); setName(""); } }; return <main className="min-h-screen bg-[#f5f7f6] p-7 lg:p-10"><header className="flex items-end justify-between gap-4"><div><h1 className="font-heading text-2xl font-extrabold text-[#132d2a]">Categories</h1><p className="mt-1 text-sm text-slate-500">Manage the maintenance services shown to customers.</p></div></header><section className="mt-5 grid gap-5 xl:grid-cols-[1fr_320px]"><div className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-bold">Service categories</h2></div><div className="divide-y divide-slate-100">{categories.map((category, index) => <div key={category} className="flex items-center gap-3 px-5 py-4"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#fff0eb] text-[#ff6224]"><Tags className="h-4 w-4" /></span><div className="flex-1"><p className="text-sm font-semibold text-[#132d2a]">{category}</p><p className="text-xs text-slate-500">{12 + index * 7} active providers</p></div><button className="rounded-md p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label={`Edit ${category}`}><Edit3 className="h-4 w-4" /></button><button onClick={() => setCategories(categories.filter(c => c !== category))} className="rounded-md p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" aria-label={`Remove ${category}`}><Trash2 className="h-4 w-4" /></button></div>)}</div></div><form onSubmit={add} className="h-fit rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-bold text-[#132d2a]">Add category</h2><p className="mt-1 text-xs text-slate-500">Create a new service type for the platform.</p><label className="mt-5 block text-xs font-bold uppercase tracking-wide text-slate-500">Category name<input value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Landscaping" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-[#ff6224]" /></label><button className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[#ff6224] px-4 py-2.5 text-sm font-bold text-white hover:bg-orange-600"><Plus className="h-4 w-4" />Add category</button></form></section></main>; }
*/
"use client";

import { FormEvent, useState } from "react";
import { Edit3, Plus, Tags, Trash2, X } from "lucide-react";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import { getCategories, saveCategories } from "@/lib/categoryStore";
export default function CategoriesPage() {
  const [categories, setCategories] = useState(() => getCategories()); const [name, setName] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [formOpen, setFormOpen] = useState(false); const [notice, setNotice] = useState("");
  const persist = (items: string[]) => { setCategories(items); saveCategories(items); };
  const submit = (event: FormEvent) => { event.preventDefault(); const value = name.trim(); if (!value) return; if (categories.some(item => item.toLowerCase() === value.toLowerCase() && item !== editing)) return setNotice("That category already exists."); persist(editing ? categories.map(item => item === editing ? value : item) : [...categories, value]); setNotice(editing ? "Category updated." : "Category added."); setName(""); setEditing(null); setFormOpen(false); };
  return <div className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><AdminPageHeader title="Categories" description="Manage service categories available on the platform" /><button onClick={() => { setEditing(null); setName(""); setFormOpen(true); }} className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white shadow-sm"><Plus size={16} />Add category</button></div>{notice && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{formOpen && <form onSubmit={submit} className="mt-5 flex flex-col gap-3 rounded-xl border border-orange-200 bg-orange-50 p-4 sm:flex-row sm:items-end"><label className="flex-1 text-sm font-semibold text-slate-700">Category name<input autoFocus value={name} onChange={event => setName(event.target.value)} required className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2" /></label><button className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">{editing ? "Save" : "Add"}</button><button type="button" onClick={() => setFormOpen(false)} className="rounded-lg border px-3 py-2 text-slate-600"><X size={16}/></button></form>}<div className="mt-5 grid gap-4 sm:grid-cols-2">{categories.map((name, index) => <article key={name} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-lg bg-orange-50 text-primary"><Tags size={18} /></span><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">Active</span></div><h2 className="mt-4 font-heading font-bold text-secondary">{name}</h2><p className="mt-1 text-sm text-slate-500">Maintenance service category visible to customers.</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-xs"><span className="text-slate-500">{12 + index * 7} technicians</span><span className="flex gap-3"><button onClick={() => { setEditing(name); setName(name); setFormOpen(true); }} className="inline-flex items-center gap-1 font-semibold text-primary"><Edit3 size={14}/>Edit</button><button onClick={() => persist(categories.filter(item => item !== name))} className="inline-flex items-center gap-1 font-semibold text-rose-600"><Trash2 size={14}/>Remove</button></span></div></article>)}</div></div>; }
