import Link from "next/link";
import { AlertTriangle, BadgeCheck, Ban, CalendarDays, ChevronRight, CircleDollarSign, ClipboardCheck } from "lucide-react";

const activity = [
  [BadgeCheck, "Patrick N. approved as verified technician", "Plumbing · by Admin (Sarah K.)", "Jul 9, 09:12", "bg-emerald-50 text-emerald-600"],
  [CircleDollarSign, "Eric N. subscription payment received", "RWF 48,000 · Annual plan via MoMo", "Jul 9, 08:47", "bg-blue-50 text-blue-600"],
  [AlertTriangle, "Grace T. application flagged for review", "Mismatched ID document · auto-flagged", "Jul 8, 17:23", "bg-amber-50 text-amber-600"],
  [Ban, "Account blocked after 3 failed login attempts", "Customer · Jeanne C. · auto-blocked", "Jul 8, 14:05", "bg-rose-50 text-rose-500"],
] as const;

const metrics = [["Total events", "1,284", "+12 today", "text-[#ff6224]"], ["Pending verification", "3", "Awaiting review", "text-[#c75b08]"], ["Payments", "21", "RWF 6.2M total", "text-blue-600"], ["Blocked accounts", "7", "2 pending review", "text-rose-500"]];

export default function Page() { return <main className="min-h-screen bg-[#f5f7f6] p-7 lg:p-10"><header className="mb-6"><h1 className="font-heading text-2xl font-extrabold text-[#132d2a]">Admin Dashboard</h1><p className="mt-1 text-sm text-slate-500">Sarah Kagabo · Platform overview</p></header><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, detail, color]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-extrabold text-[#132d2a]">{value}</p><p className={`mt-1 text-xs font-medium ${color}`}>{detail}</p></div>)}</section><section className="mt-5 flex items-center justify-between rounded-xl border border-amber-200 bg-[#fff3c9] px-4 py-3"><div className="flex items-center gap-2 text-sm font-semibold text-[#bf5b10]"><AlertTriangle className="h-4 w-4" />3 pending verifications</div><Link href="/dashboard/admin/verification" className="rounded-lg bg-[#bd590d] px-4 py-2 text-xs font-bold text-white hover:bg-[#9f4808]">Review now</Link></section><section className="mt-5"><h2 className="mb-3 text-sm font-bold text-[#132d2a]">Recent activity</h2><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{activity.map(([Icon, title, description, date, color], index) => <div key={title} className={`flex items-center gap-3 px-4 py-3 ${index ? "border-t border-slate-100" : ""}`}><span className={`grid h-7 w-7 place-items-center rounded-lg ${color}`}><Icon className="h-3.5 w-3.5" /></span><div className="min-w-0 flex-1"><p className="text-xs font-bold text-[#132d2a]">{title}</p><p className="mt-0.5 text-[11px] text-slate-500">{description}</p></div><span className="hidden text-[10px] text-slate-400 sm:block">{date}</span></div>)}</div></section><div className="mt-5 flex gap-3"><Link href="/dashboard/admin/users" className="inline-flex items-center gap-1 text-sm font-semibold text-[#b6530c] hover:underline">Manage users <ChevronRight className="h-4 w-4" /></Link><Link href="/dashboard/admin/verification" className="inline-flex items-center gap-1 text-sm font-semibold text-[#b6530c] hover:underline"><ClipboardCheck className="h-4 w-4" />Review queue</Link></div></main>; }
